language: "perl"
perl:
  - "5.16"

before_script:

install:
    - cpanm -v --installdeps --notest --mirror http://cpan.mirrors.travis-ci.org .

script: "perl Build.PL; ./Build test"
# branches:
#   only:
#     - master
notifications:
  recipients:
    - ops+travis@brewpony.com
    - jonathan+travis@brewpony.com
  email:
    on_success: change
    on_failure: change
#env:
